# Generated by Django 4.2.1 on 2023-05-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postnews',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
