# Generated by Django 4.2.1 on 2023-05-28 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0003_postcompetition'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoList1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('which_Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a1.postcompetition')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ImageList1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, null=True, upload_to='images/')),
                ('which_Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a1.postcompetition')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
